name: quizz_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  convex_bottom_bar: ^3.2.0
  bottom_bar: ^2.0.5
  font_awesome_flutter: ^10.12.0
  hugeicons: ^1.1.2
  intl: ^0.18.1
  marquee: ^2.3.0
  mobile_scanner: ^7.1.4
  flutter_math_fork: ^0.7.4
  ai_barcode_scanner: ^7.1.0
  camera: ^0.11.3
  device_info_plus: ^12.3.0
  no_screenshot: ^0.3.1
  screenshot: ^3.0.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrondH.jpg
    - .env



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoApp.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E90FF"
  adaptive_icon_foreground: "assets/images/logoApp.png"